import type { EmotionalWeatherState, MemoryStar, NarratorCue, ReplayBeat, ReplayEra } from "./types";

export const seedWeather: EmotionalWeatherState[] = [
  {
    id: "weather-stable-morning",
    tone: "stable",
    intensity: 0.52,
    auraColor: "#7dd3fc",
    skyGradient: "radial-gradient(circle at 50% 12%, rgba(125,211,252,.28), transparent 26%), linear-gradient(180deg, #020617 0%, #0f172a 48%, #000 100%)",
    cloudDensity: 0.28,
    particleDensity: 0.35,
  },
  {
    id: "weather-threshold-night",
    tone: "threshold",
    intensity: 0.84,
    auraColor: "#c084fc",
    skyGradient: "radial-gradient(circle at 50% 18%, rgba(192,132,252,.3), transparent 28%), linear-gradient(180deg, #020617 0%, #2e1065 48%, #000 100%)",
    cloudDensity: 0.66,
    particleDensity: 0.72,
  },
];

export const seedNarratorCues: NarratorCue[] = [
  {
    id: "cue-ascent",
    text: "You are rising out of the day and into the pattern beneath it.",
    voiceTone: "calm",
    delayMs: 420,
    durationMs: 4200,
    ttsEnabled: true,
    interruptible: true,
  },
  {
    id: "cue-focus",
    text: "This moment held more weight than it looked like at the time.",
    voiceTone: "warm",
    delayMs: 260,
    durationMs: 3600,
    ttsEnabled: true,
    interruptible: true,
  },
  {
    id: "cue-rebirth",
    text: "The pattern did not end. It changed shape.",
    voiceTone: "bright",
    delayMs: 250,
    durationMs: 3400,
    ttsEnabled: true,
    interruptible: true,
  },
];

export const seedStars: MemoryStar[] = [
  {
    id: "star-quiet-recovery",
    title: "Quiet Recovery",
    timestamp: "2026-05-12T19:30:00.000Z",
    emotionalTone: "recovery",
    auraColor: "#67e8f9",
    intensity: 0.72,
    x: 24,
    y: 38,
    constellationId: "constellation-recovery-arc",
    memoryType: "recovery",
    replayEligible: true,
    narratorCueId: "cue-focus",
    sourceSignals: ["sleep-rebound", "reduced-scroll", "calm-evening"],
    symbolicTags: ["blue bloom", "return", "breath"],
    bloomStyle: "softGlow",
    weatherContext: seedWeather[0],
  },
  {
    id: "star-threshold-signal",
    title: "Threshold Signal",
    timestamp: "2026-05-13T22:10:00.000Z",
    emotionalTone: "threshold",
    auraColor: "#c084fc",
    intensity: 0.9,
    x: 52,
    y: 26,
    constellationId: "constellation-recovery-arc",
    memoryType: "threshold",
    replayEligible: true,
    narratorCueId: "cue-focus",
    sourceSignals: ["late-night-activity", "message-spike", "motion-restlessness"],
    symbolicTags: ["violet gate", "crossing", "signal"],
    bloomStyle: "thresholdGate",
    weatherContext: seedWeather[1],
  },
  {
    id: "star-rebirth-pattern",
    title: "Rebirth Pattern",
    timestamp: "2026-05-14T09:05:00.000Z",
    emotionalTone: "rebirth",
    auraColor: "#fde68a",
    intensity: 0.82,
    x: 76,
    y: 46,
    constellationId: "constellation-recovery-arc",
    memoryType: "milestone",
    replayEligible: true,
    narratorCueId: "cue-rebirth",
    sourceSignals: ["early-start", "focused-session", "social-repair"],
    symbolicTags: ["gold flare", "new arc", "returning fire"],
    bloomStyle: "rebirthPulse",
    weatherContext: seedWeather[0],
  },
  {
    id: "star-ritual-anchor",
    title: "Ritual Anchor",
    timestamp: "2026-05-14T21:20:00.000Z",
    emotionalTone: "ritual",
    auraColor: "#a7f3d0",
    intensity: 0.64,
    x: 42,
    y: 58,
    constellationId: "constellation-recovery-arc",
    memoryType: "ritual",
    replayEligible: true,
    narratorCueId: "cue-focus",
    sourceSignals: ["evening-stillness", "notification-quiet", "breathing-window"],
    symbolicTags: ["green ring", "settling", "anchor"],
    bloomStyle: "constellationBloom",
    weatherContext: seedWeather[0],
  },
];

export const seedReplayEra: ReplayEra = {
  id: "era-week-you-came-back",
  title: "The Week You Came Back Online",
  subtitle: "A symbolic replay of strain, pause, and recovery.",
  startTimestamp: "2026-05-12T00:00:00.000Z",
  endTimestamp: "2026-05-15T00:00:00.000Z",
  dominantTone: "recovery",
  beatIds: ["beat-quiet-recovery", "beat-threshold-signal", "beat-rebirth-pattern"],
  progressMs: 0,
};

export const seedReplayBeats: ReplayBeat[] = [
  {
    id: "beat-quiet-recovery",
    eraId: "era-week-you-came-back",
    timestamp: "2026-05-12T19:30:00.000Z",
    starId: "star-quiet-recovery",
    beatType: "establishing",
    cameraTarget: { x: 24, y: 38, scale: 1.18, depth: 72 },
    durationMs: 4200,
    narratorCueId: "cue-ascent",
    emotionalWeatherState: seedWeather[0],
    auraState: { color: "#67e8f9", intensity: 0.58, pulseRate: 0.8 },
    transitionStyle: "drift",
    importanceScore: 0.68,
  },
  {
    id: "beat-threshold-signal",
    eraId: "era-week-you-came-back",
    timestamp: "2026-05-13T22:10:00.000Z",
    starId: "star-threshold-signal",
    beatType: "threshold",
    cameraTarget: { x: 52, y: 26, scale: 1.65, depth: 94 },
    durationMs: 5200,
    narratorCueId: "cue-focus",
    emotionalWeatherState: seedWeather[1],
    auraState: { color: "#c084fc", intensity: 0.86, pulseRate: 1.35 },
    transitionStyle: "flare",
    importanceScore: 0.92,
  },
  {
    id: "beat-rebirth-pattern",
    eraId: "era-week-you-came-back",
    timestamp: "2026-05-14T09:05:00.000Z",
    starId: "star-rebirth-pattern",
    beatType: "rebirth",
    cameraTarget: { x: 76, y: 46, scale: 1.42, depth: 88 },
    durationMs: 4800,
    narratorCueId: "cue-rebirth",
    emotionalWeatherState: seedWeather[0],
    auraState: { color: "#fde68a", intensity: 0.78, pulseRate: 1.05 },
    transitionStyle: "constellationTrace",
    importanceScore: 0.86,
  },
];
