import type { LifeMapData, LifeMapTone, MemoryStar } from './lifeMapTypes';

const tones: Record<LifeMapTone, { color: string; glyph: string }> = {
  calm: { color: 'silver-blue', glyph: 'soft-ring' },
  clarity: { color: 'cyan-white', glyph: 'clear-lens' },
  joy: { color: 'warm-gold', glyph: 'spark' },
  grief: { color: 'blue-silver', glyph: 'moon-fog' },
  stress: { color: 'amber-red', glyph: 'compressed-flame' },
  recovery: { color: 'green-gold', glyph: 'bloom-spiral' },
  dream: { color: 'violet-indigo', glyph: 'dream-eye' },
  shadow: { color: 'black-violet', glyph: 'hidden-thread' },
  threshold: { color: 'violet-gold', glyph: 'eclipse-gate' },
  rebirth: { color: 'crystal-white', glyph: 'new-star' },
  connection: { color: 'rose-blue', glyph: 'paired-orbit' },
  focus: { color: 'blue-white', glyph: 'focus-point' },
};

function star(
  id: string,
  title: string,
  subtitle: string,
  tone: LifeMapTone,
  x: number,
  y: number,
  z: number,
  importance: number,
  chapterId: MemoryStar['chapterId'],
  starType: MemoryStar['starType'],
  constellationIds: string[],
  tags: string[],
  sourceSignalIds: string[],
  narratorLine: string,
): MemoryStar {
  const meta = tones[tone];
  return {
    id,
    title,
    subtitle,
    description: `${title} became visible as a ${tone} signal in the Life Map.`,
    starType,
    timestamp: new Date(Date.now() - z * 86400000).toISOString(),
    chapterId,
    constellationIds,
    emotionalTone: tone,
    emotionalIntensity: Math.min(0.98, Math.max(0.28, importance + 0.08)),
    auraColor: meta.color,
    glyphType: meta.glyph,
    importanceScore: importance,
    confidence: Math.min(0.96, Math.max(0.56, importance + 0.12)),
    position: { x, y, z },
    visual: {
      size: 9 + Math.round(importance * 20),
      brightness: 0.48 + importance * 0.52,
      pulseSpeed: Math.max(0.18, 1.05 - importance * 0.72),
      auraRadius: 20 + importance * 54,
      particleDensity: 0.25 + importance * 0.62,
      lineWeight: 0.7 + importance * 1.5,
    },
    relatedPeopleIds: tags.includes('relationship') ? ['person-maya'] : [],
    relatedTags: tags,
    sourceSignalIds,
    narratorLine,
    privacyLevel: 'safeSummary',
    isVisible: true,
    isUnread: importance > 0.78,
  };
}

export const demoLifeMapData: LifeMapData = {
  source: 'demo',
  loading: false,
  stars: [
    star('star-quiet-return', 'The Quiet Return', 'recovery after pressure', 'recovery', 52, 52, 4, 0.88, 'recovery', 'recovery_moment', ['const-recovery-arc'], ['recovery', 'sleep'], ['sig-sleep-1', 'sig-app-1'], 'A small return appeared after pressure. Not dramatic, but real.'),
    star('star-compressed-night', 'A Compressed Night', 'late friction and shallow rest', 'shadow', 39, 59, 6, 0.82, 'shadow', 'stress_spike', ['const-shadow-loop'], ['shadow', 'sleep'], ['sig-shadow-1'], 'URAI noticed pressure collecting at night and kept it private by default.'),
    star('star-social-warmth', 'Social Warmth Returning', 'connection signal', 'connection', 63, 43, 9, 0.78, 'relationships', 'relationship_moment', ['const-social-orbit'], ['relationship', 'voice'], ['sig-voice-1'], 'A relationship orbit warmed after a quieter stretch.'),
    star('star-threshold-before-clarity', 'Threshold Before Clarity', 'crossing point', 'threshold', 49, 31, 11, 0.92, 'threshold', 'threshold_moment', ['const-threshold-rebirth'], ['threshold'], ['sig-threshold-1'], 'This was a crossing point: pressure became visible enough to name.'),
    star('star-week-softening', 'The Week of Softening', 'weekly synthesis', 'calm', 44, 45, 3, 0.7, 'becoming', 'urai_insight', ['const-weekly-scroll'], ['weeklyScroll'], ['sig-week-1'], 'The week softened from noise into steadier rhythm.'),
    star('star-repair-thread', 'The Repair Thread', 'relationship repair', 'connection', 69, 51, 13, 0.74, 'relationships', 'repair_moment', ['const-social-orbit'], ['relationship', 'repair'], ['sig-repair-1'], 'A repair signal appeared where distance had started to form.'),
    star('star-dream-symbol', 'Dream Symbol Echo', 'symbolic pattern', 'dream', 42, 66, 16, 0.68, 'dream-field', 'recurring_pattern', ['const-dream-field'], ['dream', 'symbol'], ['sig-dream-1'], 'A symbolic echo returned across several quiet moments.'),
    star('star-new-center', 'New Center', 'identity focus', 'rebirth', 58, 66, 22, 0.84, 'mirror', 'growth_marker', ['const-mirror'], ['identity', 'growth'], ['sig-mirror-1'], 'A new center began forming under the surface.'),
    star('star-overcheck-loop', 'Overcheck Loop', 'digital friction', 'stress', 35, 49, 8, 0.66, 'shadow', 'recurring_pattern', ['const-shadow-loop'], ['appUsage', 'shadow'], ['sig-app-2'], 'A repeated checking loop carried more strain than usefulness.'),
    star('star-protected-hour', 'Protected Hour', 'focus returned', 'focus', 57, 36, 2, 0.58, 'becoming', 'clarity_marker', ['const-weekly-scroll'], ['focus'], ['sig-focus-1'], 'A protected hour became a small doorway back into clarity.'),
    star('star-grief-fog', 'Blue Fog Memory', 'quiet grief marker', 'grief', 32, 42, 28, 0.64, 'becoming', 'grief_marker', ['const-seasonal-chapter'], ['grief'], ['sig-audio-2'], 'This memory carried weight, so URAI rendered it softly.'),
    star('star-ritual-ground', 'Return to Ground', 'ritual unlocked', 'recovery', 61, 56, 1, 0.76, 'recovery', 'ritual_completion', ['const-ritual-chain'], ['ritual', 'recovery'], ['sig-ritual-1'], 'A grounding ritual became available when recovery started to bloom.'),
    star('star-place-anchor', 'Place Anchor', 'location memory', 'calm', 47, 61, 18, 0.54, 'becoming', 'important_place', ['const-seasonal-chapter'], ['gps', 'place'], ['sig-gps-1'], 'A place began holding calm across repeated visits.'),
    star('star-sleep-shift', 'Sleep Shift', 'rhythm changed', 'recovery', 67, 38, 5, 0.62, 'recovery', 'sleep_shift', ['const-recovery-arc'], ['sleep'], ['sig-sleep-2'], 'Sleep timing shifted just enough to change the emotional weather.'),
    star('star-silence-trail', 'Silence Trail', 'absence pattern', 'shadow', 73, 47, 20, 0.69, 'relationships', 'social_silence', ['const-social-orbit'], ['relationship', 'absence'], ['sig-social-2'], 'A silence pattern appeared, but URAI marked it with uncertainty.'),
  ],
  constellations: [
    { id: 'const-recovery-arc', title: 'Recovery Arc', constellationType: 'recovery_arc', starIds: ['star-compressed-night', 'star-sleep-shift', 'star-quiet-return', 'star-ritual-ground'], chapterId: 'recovery', summary: 'Pressure softened into stabilization.', dominantEmotions: ['stress', 'recovery', 'calm'], symbolicTheme: 'return', confidence: 0.86, lineColor: 'green-gold', glow: 0.76, narratorLine: 'This arc shows strain becoming rhythm again.' },
    { id: 'const-social-orbit', title: 'Social Orbit', constellationType: 'relationship_arc', starIds: ['star-social-warmth', 'star-repair-thread', 'star-silence-trail'], chapterId: 'relationships', summary: 'Connection, distance, and repair formed an orbit.', dominantEmotions: ['connection', 'shadow'], symbolicTheme: 'repair', confidence: 0.78, lineColor: 'rose-blue', glow: 0.62, narratorLine: 'This relationship did not disappear; it changed shape.' },
    { id: 'const-shadow-loop', title: 'Shadow Loop', constellationType: 'stress_pattern', starIds: ['star-compressed-night', 'star-overcheck-loop'], chapterId: 'shadow', summary: 'Night pressure and digital friction repeated.', dominantEmotions: ['shadow', 'stress'], symbolicTheme: 'overload', confidence: 0.73, lineColor: 'black-violet', glow: 0.5, narratorLine: 'This pattern is shown gently because confidence is partial.' },
    { id: 'const-threshold-rebirth', title: 'Threshold to Rebirth', constellationType: 'threshold_to_rebirth', starIds: ['star-threshold-before-clarity', 'star-new-center'], chapterId: 'threshold', summary: 'A pressure point opened into identity change.', dominantEmotions: ['threshold', 'rebirth'], symbolicTheme: 'rebirth', confidence: 0.82, lineColor: 'violet-gold', glow: 0.84, narratorLine: 'A crossing point can be quiet and still change everything.' },
    { id: 'const-weekly-scroll', title: 'Week of Softening', constellationType: 'seasonal_arc', starIds: ['star-week-softening', 'star-protected-hour', 'star-quiet-return'], chapterId: 'becoming', summary: 'The week moved from noise into focus and return.', dominantEmotions: ['focus', 'recovery'], symbolicTheme: 'rhythm', confidence: 0.8, lineColor: 'silver-blue', glow: 0.58, narratorLine: 'This week did not become perfect; it became more readable.' },
    { id: 'const-dream-field', title: 'Dream Field', constellationType: 'identity_shift', starIds: ['star-dream-symbol', 'star-new-center'], chapterId: 'dream-field', summary: 'Symbolic echoes and identity signals clustered.', dominantEmotions: ['dream', 'rebirth'], symbolicTheme: 'symbol', confidence: 0.69, lineColor: 'violet-indigo', glow: 0.64, narratorLine: 'The dream field is symbolic, not literal certainty.' },
    { id: 'const-ritual-chain', title: 'Ritual Chain', constellationType: 'ritual_chain', starIds: ['star-ritual-ground', 'star-quiet-return'], chapterId: 'recovery', summary: 'A ritual was unlocked from recovery signals.', dominantEmotions: ['recovery'], symbolicTheme: 'grounding', confidence: 0.77, lineColor: 'green-gold', glow: 0.7, narratorLine: 'This ritual marks return, not achievement pressure.' },
    { id: 'const-mirror', title: 'Mirror of Becoming', constellationType: 'identity_shift', starIds: ['star-threshold-before-clarity', 'star-dream-symbol', 'star-new-center'], chapterId: 'mirror', summary: 'A long-term identity pattern is emerging.', dominantEmotions: ['threshold', 'dream', 'rebirth'], symbolicTheme: 'becoming', confidence: 0.74, lineColor: 'crystal-white', glow: 0.78, narratorLine: 'The mirror is a synthesis layer, not a verdict.' },
  ],
  blooms: [
    { id: 'bloom-quiet-return', starId: 'star-quiet-return', title: 'The Quiet Return', shortCopy: 'A small stabilization appeared after pressure.', longCopy: 'URAI noticed calmer rhythm, less digital friction, and a softer emotional signal. The Life Map translated that into a recovery bloom.', narratorReflection: 'This was not dramatic, but it mattered. Your system began to open again.', whyThis: { explanation: 'Created from sleep rhythm, app usage, and emotional tone categories. Raw private content is not shown.', sourceCategories: ['sleep', 'appUsage', 'emotionTag'], confidence: 0.86, privacyNote: 'Only a safe summary is rendered.' }, emotionalTone: 'recovery', symbolicTheme: 'return', relatedStarIds: ['star-sleep-shift', 'star-ritual-ground'], ritualSuggestionIds: ['ritual-ground'], replayScript: ['A compressed night appeared.', 'Sleep shifted.', 'A quiet return bloomed.'] },
    { id: 'bloom-threshold', starId: 'star-threshold-before-clarity', title: 'Threshold Before Clarity', shortCopy: 'A crossing point became visible.', longCopy: 'Several strain signals converged, then changed shape. URAI marks this as a threshold because the pattern became nameable.', narratorReflection: 'This was a crossing point, not a diagnosis.', whyThis: { explanation: 'Created from threshold indicators and recurring pressure signals.', sourceCategories: ['thresholdIndicator', 'shadowMetric'], confidence: 0.82, privacyNote: 'Sensitive signals are summarized only.' }, emotionalTone: 'threshold', symbolicTheme: 'crossing', relatedStarIds: ['star-new-center'], ritualSuggestionIds: ['ritual-threshold'], replayScript: ['Pressure collected.', 'The pattern became visible.', 'A new center began forming.'] },
    { id: 'bloom-social', starId: 'star-social-warmth', title: 'Social Warmth Returning', shortCopy: 'A connection signal warmed the map.', longCopy: 'Voice and interaction summaries suggested renewed warmth after a quieter stretch.', narratorReflection: 'A relationship orbit warmed without needing to be forced.', whyThis: { explanation: 'Created from social interaction and voice recognition categories.', sourceCategories: ['socialInteraction', 'voiceRecognition'], confidence: 0.78, privacyNote: 'People are shown as aliases unless the user chooses otherwise.' }, emotionalTone: 'connection', symbolicTheme: 'repair', relatedStarIds: ['star-repair-thread'], ritualSuggestionIds: ['ritual-repair'], replayScript: ['Distance appeared.', 'Warmth returned.', 'Repair became possible.'] },
  ],
  rituals: [
    { id: 'ritual-ground', title: 'Return to Ground', ritualType: 'recovery', description: 'A private ritual for marking stabilization after pressure.', linkedStarIds: ['star-quiet-return'], linkedConstellationId: 'const-recovery-arc', status: 'suggested', visualGlyph: 'green_spiral_ring', auraColor: 'green-gold', narratorLine: 'Mark this return without turning it into work.' },
    { id: 'ritual-threshold', title: 'Name the Crossing', ritualType: 'threshold', description: 'A soft ritual for naming a major transition.', linkedStarIds: ['star-threshold-before-clarity'], linkedConstellationId: 'const-threshold-rebirth', status: 'suggested', visualGlyph: 'violet_eclipse_ring', auraColor: 'violet-gold', narratorLine: 'You can name the crossing without explaining all of it.' },
    { id: 'ritual-repair', title: 'Repair Thread', ritualType: 'relationshipRepair', description: 'A relationship repair marker that stays private.', linkedStarIds: ['star-repair-thread'], linkedConstellationId: 'const-social-orbit', status: 'suggested', visualGlyph: 'paired_orbit', auraColor: 'rose-blue', narratorLine: 'Repair can be marked privately before it is spoken aloud.' },
  ],
  insights: [
    { id: 'insight-week', insightType: 'weeklyScroll', targetId: 'const-weekly-scroll', text: 'This week softened from pressure into a quieter rhythm. The important change was not intensity; it was readability.', voiceStyle: 'grounded', emotionalTone: 'recovery', safetyLevel: 'normal', sourceIds: ['star-week-softening'], confidence: 0.82 },
    { id: 'insight-shadow', insightType: 'constellation', targetId: 'const-shadow-loop', text: 'URAI noticed a repeating shadow loop. This is shown as a pattern, not a judgment.', voiceStyle: 'protective', emotionalTone: 'shadow', safetyLevel: 'sensitive', sourceIds: ['star-compressed-night'], confidence: 0.73 },
    { id: 'insight-mirror', insightType: 'mirror', targetId: 'const-mirror', text: 'A longer identity pattern is beginning to form. The Mirror should stay gentle until more evidence appears.', voiceStyle: 'minimal', emotionalTone: 'rebirth', safetyLevel: 'normal', sourceIds: ['star-new-center'], confidence: 0.74 },
  ],
  socialGraph: [
    { id: 'person-maya', personId: 'person-maya', alias: 'M.', relationshipType: 'close_friend', interactionCount30d: 9, warmthScore: 0.82, tensionScore: 0.18, trustSignal: 0.76, repairSignal: 0.44, silenceDeltaDays: 2, orbitStrength: 0.76 },
    { id: 'person-family', personId: 'person-family', alias: 'Family orbit', relationshipType: 'family', interactionCount30d: 6, warmthScore: 0.65, tensionScore: 0.28, trustSignal: 0.68, repairSignal: 0.35, silenceDeltaDays: 5, orbitStrength: 0.58 },
  ],
  recoveryArcs: [
    { id: 'recovery-cognitive', recoveryType: 'cognitive', status: 'bloomed', starIds: ['star-compressed-night', 'star-sleep-shift', 'star-quiet-return'], score: 0.74, narratorSummary: 'A recovery arc formed after overload softened into steadier rhythm.' },
  ],
  chapters: [
    { id: 'becoming', title: 'Becoming', subtitle: 'growth', dominantEmotions: ['focus', 'calm'], symbolicTheme: 'growth', summary: 'Early signals of rhythm and direction.', starIds: ['star-week-softening', 'star-protected-hour'], constellationIds: ['const-weekly-scroll'], chapterColor: 'blue-white', coverGlyph: 'seed-star', narratorSummary: 'Growth is forming through small returns.', confidence: 0.8, isActive: true },
    { id: 'threshold', title: 'Threshold', subtitle: 'crossing', dominantEmotions: ['threshold'], symbolicTheme: 'crossing', summary: 'Pressure became visible enough to name.', starIds: ['star-threshold-before-clarity'], constellationIds: ['const-threshold-rebirth'], chapterColor: 'violet-gold', coverGlyph: 'eclipse-gate', narratorSummary: 'This chapter marks a crossing.', confidence: 0.82, isActive: false },
    { id: 'recovery', title: 'Recovery', subtitle: 'softening', dominantEmotions: ['recovery'], symbolicTheme: 'return', summary: 'Signals of stabilization and return.', starIds: ['star-quiet-return', 'star-sleep-shift', 'star-ritual-ground'], constellationIds: ['const-recovery-arc'], chapterColor: 'green-gold', coverGlyph: 'bloom-spiral', narratorSummary: 'Recovery is becoming visible.', confidence: 0.86, isActive: false },
    { id: 'relationships', title: 'Relationships', subtitle: 'orbits', dominantEmotions: ['connection'], symbolicTheme: 'repair', summary: 'Connection, absence, and repair arcs.', starIds: ['star-social-warmth', 'star-repair-thread', 'star-silence-trail'], constellationIds: ['const-social-orbit'], chapterColor: 'rose-blue', coverGlyph: 'paired-orbit', narratorSummary: 'Social gravity is changing shape.', confidence: 0.78, isActive: false },
    { id: 'dream-field', title: 'Dream Field', subtitle: 'symbols', dominantEmotions: ['dream'], symbolicTheme: 'symbol', summary: 'Symbolic echoes and dream-like patterns.', starIds: ['star-dream-symbol'], constellationIds: ['const-dream-field'], chapterColor: 'violet-indigo', coverGlyph: 'dream-eye', narratorSummary: 'Symbols are gathering without certainty claims.', confidence: 0.69, isActive: false },
    { id: 'mirror', title: 'Mirror', subtitle: 'identity', dominantEmotions: ['rebirth'], symbolicTheme: 'becoming', summary: 'Long-term reflection and identity synthesis.', starIds: ['star-new-center'], constellationIds: ['const-mirror'], chapterColor: 'crystal-white', coverGlyph: 'mirror-lens', narratorSummary: 'The Mirror is forming slowly.', confidence: 0.74, isActive: false },
  ],
  moodWeather: [{ id: 'weather-week', period: 'week', moodState: 'recovery', weatherType: 'sunrise', intensity: 0.67, palette: ['green', 'gold', 'deep blue'], summary: 'The week began compressed and softened into recovery.', linkedStarIds: ['star-quiet-return', 'star-week-softening'] }],
  overlays: [
    { id: 'overlay-recovery', overlayType: 'recovery', title: 'Recovery aurora', intensity: 0.7, color: 'green-gold', starIds: ['star-quiet-return', 'star-sleep-shift'] },
    { id: 'overlay-shadow', overlayType: 'shadow', title: 'Shadow fog', intensity: 0.55, color: 'black-violet', starIds: ['star-compressed-night', 'star-overcheck-loop'] },
    { id: 'overlay-threshold', overlayType: 'threshold', title: 'Threshold eclipse', intensity: 0.78, color: 'violet-gold', starIds: ['star-threshold-before-clarity'] },
  ],
  scrollExports: [{ id: 'scroll-week', exportType: 'weekly', title: 'The Week of Softening', targetIds: ['const-weekly-scroll'], status: 'draft', format: 'html', redactionLevel: 'private', generatedText: 'This week softened from pressure into readable rhythm.' }],
  companion: { id: 'companion-main', currentMood: 'recovery', voiceStyle: 'grounded', orbColor: 'blue-gold', auraIntensity: 0.63, trustLevel: 0.72, currentPrompt: 'Click a bright memory when it feels alive. Long-press for why it appeared.', suggestedFocusStarId: 'star-quiet-return', activeMode: 'lifeMap' },
};
