import { UserFieldState, MemoryStar, ReplayScene, PassportPermission } from './types';

const GENESIS_USER_ID = 'genesis-user-001';

export const seededUserFieldState: UserFieldState = {
  userId: GENESIS_USER_ID,
  displayName: 'Genesis User',
  currentState: 'calm',
  auraColor: '#2dd4bf',
  recoveryLevel: 0.8,
  fieldIntensity: 1.2,
  lastUpdated: new Date().toISOString(),
};

export const seededMemoryStars: MemoryStar[] = [
  {
    id: 'star-1',
    userId: GENESIS_USER_ID,
    title: 'The Clearing',
    state: 'recovery',
    era: 'Last Summer',
    narratorLine: 'A moment of quiet clarity, when the fog lifted and the path forward seemed possible.',
    x: 15,
    y: 20,
    z: 0,
    intensity: 1,
    relatedStarIds: ['star-2'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'star-2',
    userId: GENESIS_USER_ID,
    title: 'Shared Silence',
    state: 'bond',
    era: 'Two Years Ago',
    narratorLine: 'No words were needed. In the quiet space between, a universe of understanding was found.',
    x: 30,
    y: 45,
    z: 0,
    intensity: 0.8,
    relatedStarIds: ['star-3', 'star-5'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'star-3',
    userId: GENESIS_USER_ID,
    title: 'The Edge of the World',
    state: 'threshold',
    era: 'Childhood',
    narratorLine: 'Standing at the precipice of a great unknown, fear and wonder intertwined.',
    x: 75,
    y: 60,
    z: 0,
    intensity: 0.9,
    relatedStarIds: ['star-4'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'star-4',
    userId: GENESIS_USER_ID,
    title: 'Midnight Haze',
    state: 'blueFog',
    era: 'Last Month',
    narratorLine: 'A period of uncertainty, where thoughts drifted like smoke and clarity was a distant shore.',
    x: 85,
    y: 25,
    z: 0,
    intensity: 0.7,
    relatedStarIds: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'star-5',
    userId: GENESIS_USER_ID,
    title: 'Rearview Mirror',
    state: 'reflection',
    era: 'A Decade Ago',
    narratorLine: 'Looking back, the patterns became clear, a map drawn from moments of impact.',
    x: 50,
    y: 80,
    z: 0,
    intensity: 1.1,
    relatedStarIds: [],
    createdAt: new Date().toISOString(),
  },
];

export const seededReplayScenes: ReplayScene[] = [
    {
      id: 'scene-1',
      userId: GENESIS_USER_ID,
      title: 'The Clearing',
      state: 'recovery',
      era: 'Last Summer',
      narratorLine: 'A moment of quiet clarity, when the fog lifted and the path forward seemed possible.',
      duration: 10,
      order: 1,
      memoryStarId: 'star-1',
    },
    {
      id: 'scene-2',
      userId: GENESIS_USER_ID,
      title: 'Shared Silence',
      state: 'bond',
      era: 'Two Years Ago',
      narratorLine: 'No words were needed. In the quiet space between, a universe of understanding was found.',
      duration: 8,
      order: 2,
      memoryStarId: 'star-2',
    },
    {
      id: 'scene-3',
      userId: GENESIS_USER_ID,
      title: 'The Edge of the World',
      state: 'threshold',
      era: 'Childhood',
      narratorLine: 'Standing at the precipice of a great unknown, fear and wonder intertwined.',
      duration: 12,
      order: 3,
      memoryStarId: 'star-3',
    },
];

export const seededPassportPermissions: PassportPermission[] = [
  { id: 'perm-audio', userId: GENESIS_USER_ID, category: 'Audio', enabled: false, sensitivity: 'high', description: 'Access to microphone for ambient sound analysis.', updatedAt: new Date().toISOString() },
  { id: 'perm-location', userId: GENESIS_USER_ID, category: 'Location', enabled: false, sensitivity: 'high', description: 'Access to location data for spatial awareness.', updatedAt: new Date().toISOString() },
  { id: 'perm-motion', userId: GENESIS_USER_ID, category: 'Motion', enabled: false, sensitivity: 'medium', description: 'Access to motion and fitness data.', updatedAt: new Date().toISOString() },
  { id: 'perm-calendar', userId: GENESIS_USER_ID, category: 'Calendar', enabled: false, sensitivity: 'medium', description: 'Access to calendar events and schedule.', updatedAt: new Date().toISOString() },
  { id: 'perm-contacts', userId: GENESIS_USER_ID, category: 'Contacts', enabled: false, sensitivity: 'high', description: 'Access to contacts and communication patterns.', updatedAt: new Date().toISOString() },
  { id: 'perm-gmail', userId: GENESIS_USER_ID, category: 'Gmail', enabled: false, sensitivity: 'high', description: 'Access to Gmail for content analysis.', updatedAt: new Date().toISOString() },
  { id: 'perm-photos', userId: GENESIS_USER_ID, category: 'Photos / Camera', enabled: false, sensitivity: 'high', description: 'Access to photos and camera for visual analysis.', updatedAt: new Date().toISOString() },
  { id: 'perm-device', userId: GENESIS_USER_ID, category: 'Device Activity', enabled: false, sensitivity: 'medium', description: 'Access to device activity and usage patterns.', updatedAt: new Date().toISOString() },
  { id: 'perm-health', userId: GENESIS_USER_ID, category: 'Health Signals', enabled: false, sensitivity: 'high', description: 'Access to health data from connected devices.', updatedAt: new Date().toISOString() },
  { id: 'perm-notifications', userId: GENESIS_USER_ID, category: 'Notifications', enabled: false, sensitivity: 'low', description: 'Access to notifications for real-time alerts.', updatedAt: new Date().toISOString() },
];
