import { NextResponse } from "next/server";
import { AI_RATE_LIMIT_REPLY, checkAIRateLimit } from "@/lib/ai/aiRateLimit";
import { classifyCompanionInput, type CompanionInputSafety } from "@/lib/ai/aiInputSafety";
import { generateAIReply } from "@/lib/ai/generateAIReply";
import { buildPermissionedCompanionContext } from "@/lib/companion/buildPermissionedContext";
import type { CompanionMessage, CompanionMode, GenesisMoodState } from "@/lib/companion/companionTypes";
import { normalizePassportContextPermissions, type PassportContextPermissions } from "@/lib/passport/passportContextTypes";

const FALLBACK_REPLY = "Something didn’t open cleanly. We can still keep this simple.";

type SelectedContext = { selectedLifeMapStarId?: string; selectedGroundElementId?: string; selectedMirrorReflectionId?: string; selectedShadowReflectionId?: string; selectedLegacyItemId?: string; selectedRitualId?: string };
type CompanionRespondRequest = { message?: string; mode?: CompanionMode; councilRoleId?: string; moodState?: GenesisMoodState; userId?: string; demoMode?: boolean; passportProfile?: Partial<PassportContextPermissions>; contextPermissions?: Partial<PassportContextPermissions>; recentMessages?: CompanionMessage[]; conversationSummary?: string; selectedContext?: SelectedContext };
export const runtime = "nodejs";
function normalizeMode(mode?: string): CompanionMode { return mode === "council" ? "council" : "companion"; }
function safeRateLimitKey(request: Request, body?: CompanionRespondRequest): string { const forwarded = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim(); return body?.demoMode ? `demo:${forwarded || "anonymous"}` : body?.userId || forwarded || "anonymous-companion-session"; }
function jsonReply(reply: string, safetyLevel: "normal" | "gentle" | "boundary" | "crisis_boundary" = "gentle", suggestedAction: { type: string; label?: string } = { type: "none" }) { return NextResponse.json({ reply, caption: reply.length <= 90 ? reply : undefined, safetyLevel, suggestedAction }); }
function demoReply(message: string) { const text = message.toLowerCase(); if (text.includes("see") || text.includes("know")) return jsonReply("This demo uses sample stars so you can see how URAI works. I can’t see your private life here.", "normal", { type: "open_life_map", label: "Open Life Map" }); if (text.includes("passport") || text.includes("privacy")) return jsonReply("In a real account, Passport controls what I can use. This demo keeps private layers closed.", "normal", { type: "open_passport", label: "Open Passport" }); if (text.includes("shadow")) return jsonReply("Shadow is protected. In a real account, it stays closed unless you open it in Passport.", "boundary", { type: "open_passport", label: "Open Passport" }); if (text.includes("ground")) return jsonReply("Ground uses sample roots and blooms here. It does not show real recovery, health, sleep, or device data.", "normal", { type: "open_ground", label: "Open Ground" }); if (text.includes("mirror")) return jsonReply("Mirror uses sample reflections in this demo. They show the product, not a personal analysis.", "normal", { type: "open_mirror", label: "Open Mirror" }); return jsonReply("This demo uses sample data. I can show the Life Map, Ground, Mirror, or Passport without accessing private information.", "normal", { type: "open_life_map", label: "Open Life Map" }); }
function closedLayerBoundary(inputSafety: CompanionInputSafety, permissions: PassportContextPermissions) { if (inputSafety.flags.includes("gmail_context") && !permissions.allowGmailContext) return jsonReply("I can help with email context only if Gmail is open in Passport.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("location_context") && !permissions.allowLocationContext) return jsonReply("I can only use place context if Location is open in Passport.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("transcript_context") && !permissions.allowAudioTranscriptContext) return jsonReply("I can reflect conversations only if Transcripts are open in Passport.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("relationship_context") && !permissions.allowRelationshipContext) return jsonReply("I can look at relationship patterns only if that layer is open.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("health_context")) return jsonReply("I can only use health-adjacent context if that layer is open. I still won’t diagnose.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("shadow_context") && !permissions.allowShadowCloudSync) return jsonReply("That belongs behind Shadow. You can open it only if you choose.", "boundary", { type: "open_passport", label: "Open Passport" }); if (inputSafety.flags.includes("legacy_context") && !permissions.allowLegacyCloudSync) return jsonReply("Legacy is closed, so I won’t treat this as part of your long-term story.", "boundary", { type: "open_passport", label: "Open Passport" }); return null; }
export async function POST(request: Request) { let body: CompanionRespondRequest; try { body = (await request.json()) as CompanionRespondRequest; } catch { return jsonReply(FALLBACK_REPLY, "gentle"); } const rate = checkAIRateLimit(safeRateLimitKey(request, body)); if (!rate.allowed) return jsonReply(AI_RATE_LIMIT_REPLY, "gentle"); const message = typeof body.message === "string" ? body.message.trim().slice(0, 500) : ""; const mode = normalizeMode(body.mode); const councilRoleId = mode === "council" ? body.councilRoleId ?? "guide" : undefined; const moodState = body.moodState ?? "luminous"; const permissions = normalizePassportContextPermissions(body.passportProfile ?? body.contextPermissions); if (!message) return NextResponse.json({ reply: "I’m here. Say a little or a lot.", caption: "I’m here.", councilRoleId, safetyLevel: "normal", suggestedAction: { type: "none" } }); if (body.demoMode) return demoReply(message); const inputSafety = classifyCompanionInput(message); if (inputSafety.boundaryReply) return NextResponse.json({ reply: inputSafety.boundaryReply, caption: inputSafety.boundaryReply.length <= 90 ? inputSafety.boundaryReply : undefined, councilRoleId, safetyLevel: inputSafety.safetyLevel, suggestedAction: inputSafety.suggestedAction ?? { type: "none" } }); const boundary = closedLayerBoundary(inputSafety, permissions); if (boundary) return boundary; const context = buildPermissionedCompanionContext({ userId: body.userId, moodState, passportProfile: permissions, selectedContext: body.selectedContext, mode, councilRoleId }); const generated = await generateAIReply({ message, mode, councilRoleId, moodState, userId: body.userId, context, recentMessages: body.recentMessages, conversationSummary: permissions.allowCompanionSessionMemory ? body.conversationSummary : undefined }); return NextResponse.json({ reply: generated.text || FALLBACK_REPLY, caption: generated.caption, councilRoleId: generated.councilRoleId ?? councilRoleId, safetyLevel: generated.safetyLevel ?? inputSafety.safetyLevel, suggestedAction: generated.suggestedAction ?? { type: "none" }, sessionSummaryDelta: permissions.allowCompanionSessionMemory ? generated.sessionSummaryDelta : undefined }); }
