################################################################
# 1️⃣ CLEAN + PREP FOLDER STRUCTURE
################################################################
mkdir -p src/config src/components src/pages src/utils functions/src

# Create fresh feature flags file
cat > src/config/featureFlags.ts << 'EOF'
export const featureFlags = {
  // Phase 1 — Core Spine
  auth: true,
  passiveAudioCapture: true,
  gpsTrackingBasic: true,
  aiTaggingPipeline: true,
  basicInsightDisplay: true,

  // Disabled for now
  dreamMap: false,
  seasonalSkyAnimations: false,
  riveParticleMoodLayers: false,
  gmailIntegration: false,
  hapticFeedback: false,
  shadowCognition: false,
  obscuraPatterns: false,
  socialGraph: false,
  voiceDreamFusion: false,
  insightMarketplace: false,

  // Debug
  debugLogging: true
};
EOF

################################################################
# 2️⃣ FIRESTORE RULES
################################################################
cat > firestore.rules << 'EOF'
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    // Users can read/write their own data
    match /users/{userId} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
    }

    // Insights generated by AI
    match /insights/{docId} {
      allow read, write: if request.auth != null;
    }
  }
}
EOF
firebase deploy --only firestore:rules

################################################################
# 3️⃣ MINIMAL FUNCTIONS INDEX
################################################################
cat > functions/src/index.ts << 'EOF'
import * as functions from "firebase-functions";
import { audioTranscriber } from "./audioTranscriber";
import { aiTagger } from "./aiTagger";

// Keep only essential functions for alpha
export const transcribeAudio = audioTranscriber;
export const tagAI = aiTagger;
EOF

firebase deploy --only functions

################################################################
# 4️⃣ DEPLOY HOSTING
################################################################
npm run build
firebase deploy --only hosting
