
import type { PassportLayerDefinition, PassportLayerId } from "./passportLayerTypes";

export const passportLayerRegistry: Record<PassportLayerId, PassportLayerDefinition> = {
  passive_data: {
    id: "passive_data",
    title: "Passive Data Ingestion",
    summary: "Allows URAI to collect data from your device and accounts in the background.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  intelligence: {
    id: "intelligence",
    title: "Intelligence Engine",
    summary: "Allows URAI's AI to process your data to provide insights and recommendations.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  companion_context: {
    id: "companion_context",
    title: "Companion Context",
    summary: "Allows the URAI Companion to access your data to provide personalized assistance.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  lifemap: {
    id: "lifemap",
    title: "Life Map",
    summary: "Generates a visualization of your life based on your data.",
    sensitivity: "medium",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  ground: {
    id: "ground",
    title: "Ground",
    summary: "Grounds your URAI experience in your real-world activities and locations.",
    sensitivity: "medium",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  mirror: {
    id: "mirror",
    title: "Mirror",
    summary: "Reflects your digital self, showing you how URAI sees you.",
    sensitivity: "medium",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  shadow: {
    id: "shadow",
    title: "Shadow",
    summary: "Analyzes your unconscious patterns and biases.",
    sensitivity: "protected",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  legacy: {
    id: "legacy",
    title: "Legacy",
    summary: "Creates a lasting digital legacy based on your life's data.",
    sensitivity: "protected",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  export: {
    id: "export",
    title: "Export",
    summary: "Allows you to export your data from URAI.",
    sensitivity: "medium",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  notifications: {
    id: "notifications",
    title: "Notifications",
    summary: "Allows URAI to send you notifications.",
    sensitivity: "low",
    defaultStatus: "closed",
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  spatial: {
    id: "spatial",
    title: "Spatial Computing",
    summary: "Integrates URAI with augmented and virtual reality devices.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  audio: {
    id: "audio",
    title: "Audio Capture",
    summary: "Allows URAI to capture and process audio from your microphone.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  location: {
    id: "location",
    title: "Location Tracking",
    summary: "Allows URAI to track your device's location.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  health: {
    id: "health",
    title: "Health Data",
    summary: "Allows URAI to access your health and fitness data.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  gmail: {
    id: "gmail",
    title: "Gmail Integration",
    summary: "Allows URAI to access your Gmail account.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  calendar: {
    id: "calendar",
    title: "Calendar Integration",
    summary: "Allows URAI to access your calendar.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  contacts: {
    id: "contacts",
    title: "Contacts Integration",
    summary: "Allows URAI to access your contacts.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  motion: {
    id: "motion",
    title: "Motion & Fitness",
    summary: "Allows URAI to access your motion and fitness data.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  camera: {
    id: "camera",
    title: "Camera Access",
    summary: "Allows URAI to access your device's camera.",
    sensitivity: "high",
    defaultStatus: "closed",
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  admin: {
    id: "admin",
    title: "Admin Access",
    summary: "Provides administrative access to URAI systems.",
    sensitivity: "protected",
    defaultStatus: "blocked",
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  system: {
    id: "system",
    title: "System",
    summary: "Core system functionalities.",
    sensitivity: "low",
    defaultStatus: "open",
    requiresExplicitApproval: false,
    canBeOpenedByUser: false,
  },
};
