
import { PassportLayerId, PassportLayerStatus, PassportLayerSensitivity } from './keys';

export interface PassportLayerDefinition {
  id: PassportLayerId;
  title: string;
  summary: string;
  sensitivity: PassportLayerSensitivity;
  defaultStatus: PassportLayerStatus;
  requiresExplicitApproval: boolean;
  canBeOpenedByUser: boolean;
}

export const PASSPORT_LAYER_DEFINITIONS: Record<PassportLayerId, PassportLayerDefinition> = {
  passive_data: {
    id: 'passive_data',
    title: 'Passive Data',
    summary: 'Collects data from your device sensors and app usage.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  intelligence: {
    id: 'intelligence',
    title: 'Intelligence',
    summary: 'Provides personalized insights and recommendations.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  companion_context: {
    id: 'companion_context',
    title: 'Companion Context',
    summary: 'Allows your companion to understand your context and provide relevant assistance.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  lifemap: {
    id: 'lifemap',
    title: 'Lifemap',
    summary: 'Visualizes your life and experiences.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  ground: {
    id: 'ground',
    title: 'Ground',
    summary: 'Connects you with your physical environment.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  mirror: {
    id: 'mirror',
    title: 'Mirror',
    summary: 'Reflects your emotions and well-being.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  shadow: {
    id: 'shadow',
    title: 'Shadow',
    summary: 'Handles sensitive and private data.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  legacy: {
    id: 'legacy',
    title: 'Legacy',
    summary: 'Manages your digital legacy.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  export: {
    id: 'export',
    title: 'Export',
    summary: 'Exports your data.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  notifications: {
    id: 'notifications',
    title: 'Notifications',
    summary: 'Sends you notifications.',
    sensitivity: 'low',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  spatial: {
    id: 'spatial',
    title: 'Spatial',
    summary: 'Accesses your spatial data.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  audio: {
    id: 'audio',
    title: 'Audio',
    summary: 'Accesses your microphone.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  location: {
    id: 'location',
    title: 'Location',
    summary: 'Accesses your location data.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  health: {
    id: 'health',
    title: 'Health',
    summary: 'Accesses your health data.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  gmail: {
    id: 'gmail',
    title: 'Gmail',
    summary: 'Accesses your Gmail data.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  calendar: {
    id: 'calendar',
    title: 'Calendar',
    summary: 'Accesses your calendar data.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  contacts: {
    id: 'contacts',
    title: 'Contacts',
    summary: 'Accesses your contacts.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  motion: {
    id: 'motion',
    title: 'Motion',
    summary: 'Accesses your motion data.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  camera: {
    id: 'camera',
    title: 'Camera',
    summary: 'Accesses your camera.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  admin: {
    id: 'admin',
    title: 'Admin',
    summary: 'Provides administrative access.',
    sensitivity: 'protected',
    defaultStatus: 'blocked',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  system: {
    id: 'system',
    title: 'System',
    summary: 'Provides system-level access.',
    sensitivity: 'low',
    defaultStatus: 'open',
    requiresExplicitApproval: false,
    canBeOpenedByUser: false,
  },
};
