import { PassportLayerId, PassportLayerStatus, PassportLayerSensitivity } from './keys';

export interface PassportLayerDefinition {
  id: PassportLayerId;
  title: string;
  summary: string;
  sensitivity: PassportLayerSensitivity;
  defaultStatus: PassportLayerStatus;
  requiresExplicitApproval: boolean;
  canBeOpenedByUser: boolean;
}

export const PASSPORT_LAYER_DEFINITIONS: Record<PassportLayerId, PassportLayerDefinition> = {
  passive_data: {
    id: 'passive_data',
    title: 'Passive Data',
    summary: 'Records whether future passive sources may be reviewed. Collection stays off until separate consent and device/account permission are complete.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  intelligence: {
    id: 'intelligence',
    title: 'Intelligence',
    summary: 'Allows approved URAI reflection layers to use consented signals for guidance. It does not unlock private data by itself.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  companion_context: {
    id: 'companion_context',
    title: 'Companion Context',
    summary: 'Lets the companion use only the context you explicitly open. Closed or protected sources remain unavailable.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  lifemap: {
    id: 'lifemap',
    title: 'Life Map',
    summary: 'Turns approved memories and sample stars into the Life Map experience. Private memories require owner approval before use.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  ground: {
    id: 'ground',
    title: 'Ground',
    summary: 'Controls grounded reflection and action cues. Device, location, or health data require separate permission before use.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  mirror: {
    id: 'mirror',
    title: 'Mirror',
    summary: 'Shows reflection prompts and emotional-weather language without diagnosis or hidden sensing.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  shadow: {
    id: 'shadow',
    title: 'Shadow',
    summary: 'A sealed protected layer for sensitive reflection. It stays closed until a separate review flow is available.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  legacy: {
    id: 'legacy',
    title: 'Legacy',
    summary: 'A sealed legacy layer for long-term memory and sharing decisions. It requires explicit review before anything is revealed.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  export: {
    id: 'export',
    title: 'Export',
    summary: 'A protected export boundary. Exports require verification, scope review, and owner approval before files are created.',
    sensitivity: 'protected',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  notifications: {
    id: 'notifications',
    title: 'Notifications',
    summary: 'Records whether URAI may prepare notification preferences. Browser or device permission remains a separate step.',
    sensitivity: 'low',
    defaultStatus: 'closed',
    requiresExplicitApproval: false,
    canBeOpenedByUser: true,
  },
  spatial: {
    id: 'spatial',
    title: 'Spatial',
    summary: 'Controls spatial preview preferences. Real XR/device access remains gated until provider, device, and privacy proof exists.',
    sensitivity: 'medium',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  audio: {
    id: 'audio',
    title: 'Audio',
    summary: 'Records an audio preference only. Microphone capture requires an explicit browser/device permission step and live gates.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  location: {
    id: 'location',
    title: 'Location',
    summary: 'Records a location preference only. Location collection requires separate device permission and explicit consent.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  health: {
    id: 'health',
    title: 'Health',
    summary: 'Records a health-adjacent preference only. Health data remains unavailable without explicit source authorization.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  gmail: {
    id: 'gmail',
    title: 'Gmail',
    summary: 'Records a Gmail preference only. OAuth connection and scope review are required before any mailbox data could be used.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  calendar: {
    id: 'calendar',
    title: 'Calendar',
    summary: 'Records a calendar preference only. Account authorization is required before any calendar data could be used.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  contacts: {
    id: 'contacts',
    title: 'Contacts',
    summary: 'Records a contacts preference only. Contact access requires separate account or device permission.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  motion: {
    id: 'motion',
    title: 'Motion',
    summary: 'Records a motion preference only. Motion or device activity collection is off until explicit permission is completed.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  camera: {
    id: 'camera',
    title: 'Camera',
    summary: 'Records a camera preference only. Camera use requires explicit browser/device permission and a live capture flow.',
    sensitivity: 'high',
    defaultStatus: 'closed',
    requiresExplicitApproval: true,
    canBeOpenedByUser: true,
  },
  admin: {
    id: 'admin',
    title: 'Admin',
    summary: 'Restricted operational controls. This cannot be opened by a public user and does not expose private data.',
    sensitivity: 'protected',
    defaultStatus: 'blocked',
    requiresExplicitApproval: true,
    canBeOpenedByUser: false,
  },
  system: {
    id: 'system',
    title: 'System',
    summary: 'Keeps launch-safe system status visible without granting device, account, or private-data access.',
    sensitivity: 'low',
    defaultStatus: 'open',
    requiresExplicitApproval: false,
    canBeOpenedByUser: false,
  },
};
