name: ci
on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Detect PM
        id: pm
        run: |
          if [ -f pnpm-lock.yaml ]; then echo "pm=pnpm" >> $GITHUB_OUTPUT; else echo "pm=npm" >> $GITHUB_OUTPUT; fi
      - name: Setup PM
        if: steps.pm.outputs.pm == 'pnpm'
        uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install deps
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = pnpm ]; then pnpm install --frozen-lockfile; else npm ci || npm i; fi
      - name: Typecheck
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = pnpm ]; then pnpm exec tsc --noEmit; else npx tsc --noEmit; fi
      - name: Lint
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = pnpm ]; then pnpm exec eslint .; else npx eslint .; fi
      - name: Test
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = pnpm ]; then pnpm run test; else npm run test; fi
